### PR TITLE
fix panic when parsing source file with lines larger than u16::MAX

### LINKED ISSUE #341: Panic in exception_public.rs: Column number overflow (TryFromIntError) when executing code with long lines
## Bug

When Monty processes a file where any line is ≥ 65536 characters long, it panics with:

```
thread '<unnamed>' panicked at crates/monty/src/exception_public.rs:346:43:
Column number overflow: TryFromIntError(())
```

This surfaces in Python as a `pyo3_runtime.PanicException` and kills the process instead of returning a normal exception.

## Minimal reproduction

```python
from pydantic_monty import Monty

# Any line >= 65536 chars triggers the panic.
# The line itself can be valid Python — the panic occurs when Monty
# records a file position (e.g. for a NameError on the *next* line).
code = "x = " + "a" * 65532 + "\ny = undefined_name"  # line 1 is exactly 65536 chars
Monty(code)  # raises pyo3_runtime.PanicException: Column number overflow: TryFromIntError(())
```

Verified boundary:
- Line length 65535 → `MontyNameError` (correct, graceful)
- Line length 65536 → **panic**

## Root cause

Column offsets appear to be stored as `u16` (max 65535). A line of ≥ 65536 characters causes `TryFromIntError` when converting the byte offset to `u16` at `exception_public.rs:346`.

## Context

- **pydantic-monty version**: 0.0.12
- **pydantic-ai-harness version**: 0.1.1
- Triggered in production when an LLM generates a long single-line Python expression inside a CodeMode tool call

## Expected behavior

Graceful `MontyNameError` (or similar) rather than a process-level panic. Options: clamp to `u16::MAX`, use `u32`, or saturate.

### PR DESCRIPTION
**Pull request by davidhewitt**
Fixes #341 

I changed `CodeLoc` to use `u32` indexing to match ruff. Claude spotted a separate bug related to non-ascii char offsets while analysing this change.

### CODE REVIEW

File: crates/monty/src/exception_public.rs [hunk 1]
```diff
@@ -333,17 +336,18 @@ impl Default for CodeLoc {
...
+    /// Panics if the 0-based line or column equals `u32::MAX` (i.e. would
+    /// overflow when shifted to 1-based).
     #[must_use]
-    pub fn new(line: usize, column: usize) -> Self {
+    pub fn new(line: u32, column: u32) -> Self {
         Self {
-            line: u16::try_from(line).expect("Line number overflow") + 1,
-            column: u16::try_from(column).expect("Column number overflow") + 1,
+            line: line.checked_add(1).expect("line number overflow"),
+            column: column.checked_add(1).expect("column number overflow"),
```
Comment (samuelcolvin) [inline crates/monty/src/exception_public.rs]:
```suggestion
            line: line.saturating_add(1),
            column: column.saturating_add(1),
```

maybe we keep things simple and avoid potential panic where possible, even if it's now extremely unlikely.

File: crates/monty/src/parse.rs [hunk 2]
```diff
@@ -1762,3 +1774,37 @@ fn parse_int_literal(s: &str, position: CodeRange) -> Result<BigInt, ParseError>
             .map_err(|e| ParseError::syntax(format!("invalid integer literal {s:?}, error: {e}"), position))
     }
 }
+
+#[cfg(test)]
+mod tests {
+    use crate::{ExcType, MontyRun};
```
Comment (samuelcolvin) [inline crates/monty/src/parse.rs]: if these don't need internal types, I'd rather the tests go in the main body of tests.

**Review by samuelcolvin — COMMENTED** [review]
otherwise LGTM

File: crates/monty/src/exception_public.rs
[the remark this answers is not in the document]
Comment (davidhewitt) [reply crates/monty/src/exception_public.rs:1]: #343
